preload = /home/sprocto/SFP/FrostpunkIIWallpaper.jpg

wallpaper {
    monitor = DP-1
    path = /home/sprocto/SFP/FrostpunkIIWallpaper.jpg
}
wallpaper {
    monitor = DP-2
    path = /home/sprocto/SFP/FrostpunkIIWallpaper.jpg
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/sprocto/SFP/FrostpunkIIWallpaper.jpg
}

splash = false